[language-server.rust-analyzer.config]
cargo = { targetDir = true }
diagnostics = { enable = true }
checkOnSave =  { enable = true }
lens = { enable = true }
procMacro = { enable = true, ignored = {leptos_macro = ["server"]} }


